### ISSUE TITLE
Using the given commands for Homo sapiens I am left with 0 rRNAs

### ISSUE THREAD

**Issue by bharati16mehani** [igordot/genomics#3]
Hi I used the given method to create the ribosomal RNA reference sequence using Rfam 14.1 for humans (species="homo_sapiens"). After following all your steps I am left with 0 rRNAs in order to proceed for quantifying rRNAs in my RNA Seq data set.

I am looking for any solution to my problem.
Thanks

**Comment by igordot** [comment]
I originally wrote the workflow based on version 12.0, released more than 3 years ago. It should still work for that version. Rfam changed the formatting of their files in the more recent releases.

More recently, I started using RNAcentral, which aggregates data from multiple databases, including Rfam. I updated the workflow to use RNAcentral files.
