### ISSUE TITLE
stop codon

### ISSUE THREAD

**Issue by graeberlab** [igordot/genomics#4]
THere is no stop codon. Not sure if there is more sequence following the AAG, or there should be a stop. But just wanted to let you know.

**Comment by igordot** [comment]
Sorry. What was this in reference to?

**Comment by graeberlab** [comment]
Oh im sorry the gfp sequence on your make a gfp gtf tutorial seems to lack
a stop codon. Was not sure whether the sequence got cut off in a cut and
paste.  But  now looked an another egfp sequence from a plasmid I have and
it seems you are just missing a TAA at the end of your sequence in that
tutorial. Sorry if unclear does that make sense?

**Comment by igordot** [comment]
I think I got the sequence from [Common DNA Sequences](https://www.algosome.com/resources/common-sequences.html). I am not sure why they exclude the stop codon. Many other sequences on that page have it.

**Comment by graeberlab** [comment]
Yup just updating you so it can be fixed. Honestly thought there was
missimg coding sequence but it just seems the stop is missing.
