### ISSUE TITLE
Adding EGFP to ENCODE cDNA.fa

### ISSUE THREAD

**Issue by amitpande74** [igordot/genomics#6]
HI,
What should be in file format for adding the GFP to the cDNA file ?
I am trying to add 
```
>GFP
ATGCCCGCCATGAAGATCGAGTGCCGCATCACCGGCACCCTGAACGGCGTGGAGTTCGAGCTGGTGGGCGGCGGAGAGGGCACCCCCGAGCAGGGCCGCATGACCAACAAGATGAA
GAGCACCAAAGGCGCCCTGACCTTCAGCCCCTACCTGCTGAGCCACGTGATGGGCTACGGCTTCTACCACTTCGGCACCTACCCCAGCGGCTACGAGAACCCCTTCCTGCACGCCA
TCAACAACGGCGGCTACACCAACACCCGCATCGAGAAGTACGAGGACGGCGGCGTGCTGCACGTGAGCTTCAGCTACCGCTACGAGGCCGGCCGCGTGATCGGCGACTTCAAGGTG
GTGGGCACCGGCTTCCCCGAGGACAGCGTGATCTTCACCGACAAGATCATCCGCAGCAACGCCACCGTGGAGCACCTGCACCCCATGGGCGATAACGTGCTGGTGGGCAGCTTCGC
CCGCACCTTCAGCCTGCGCGACGGCGGCTACTACAGCTTCGTGGTGGACAGCCACATGCACTTCAAGAGCGCCATCCACCCCAGCATCCTGCAGAACGGGGGCCCCATGTTCGCCT
TCCGCCGCGTGGAGGAGCTGCACAGCAACACCGAGCTGGGCATCGTGGAGTACCAGCACGCCTTCAAGACCCCCATCGCCTTCGCC
```
and what about the decoys ?
Kindly help. Since here something else is mentioned 
`https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/`
regards,
Amit.

**Comment by igordot** [comment]
I haven't tried it myself, but that should work.

Salmon docs includes [a section on how to build a decoy-aware transcriptome file](https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode).

**Comment by amitpande74** [comment]
Hi,

./generateDecoyTranscriptome.sh [-j <N> =1 default] [-b <bedtools binary path> =bedtools default] [-m <mashmap binary path> =mashmap default] -a <gtf file> -g <genome fasta> -t <txome fasta> -o <output path>

When I ran the analysis:

./generateDecoyTranscriptome.sh -b /usr/local/bin/bedtools -m /home/amit/miniconda3/bin/mashmap -a ../hg19.ncbiRefseq.added.gtf -g ../hg19_added_genes.fa -t ../Homo_sapiens.GRCh38.cdna.all.fa -o /home/amit/Downloads/SalmonTools-master/sb_results
****************
*** getDecoy ***
****************
-b <bedtools binary> = /usr/local/bin/bedtools
-m <mashmap binary> = /home/amit/miniconda3/bin/mashmap
-a <Annotation GTF file> = /home/amit/Downloads/SalmonTools-master/hg19.ncbiRefseq.added.gtf
-g <Genome fasta> = /home/amit/Downloads/SalmonTools-master/hg19_added_genes.fa
-t <Transcriptome fasta> = /home/amit/Downloads/SalmonTools-master/Homo_sapiens.GRCh38.cdna.all.fa
-o <Output files Path> = /home/amit/Downloads/SalmonTools-master/sb_results
[1/10] Extracting exonic features from the gtf
[2/10] Masking the genome fasta
[3/10] Aligning transcriptome to genome
>>>>>>>>>>>>>>>>>>
Reference = [reference.masked.genome.fa]
Query = [/home/amit/Downloads/SalmonTools-master/Homo_sapiens.GRCh38.cdna.all.fa]
Kmer size = 16
Window size = 5
Segment length = 500 (read split allowed)
Alphabet = DNA
Percentage identity threshold = 80%
Mapping output file = mashmap.out
Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
Execution threads  = 1
>>>>>>>>>>>>>>>>>>
INFO, skch::Sketch::build, minimizers picked from reference = 937226701
./generateDecoyTranscriptome.sh: line 105: 14872 Segmentation fault      (core dumped) $mashmap -r reference.masked.genome.fa -q $txpfile -t $threads --pi 80 -s 500

***************
*** ABORTED ***
***************

An error occurred. Exiting...

Kindly guide.

**Comment by igordot** [comment]
I am not sure why you are getting an error. I think this would be a question for the Salmon developers. I would first try to run this on unmodified reference files just to make sure everything is working. Additionally, based on the file names, it looks like you are mixing hg19 and hg38 files which will definitely cause issues.
