### ISSUE TITLE
hg19 or hg38

### ISSUE THREAD

**Issue by UNSWGiiGii** [igordot/genomics#9]
Hi, is anyone sure if the ribosome fasta file created is hg19 or hg38?

**Comment by igordot** [comment]
Are you referring to the [Creating ribosomal RNA reference sequence](https://github.com/igordot/genomics/blob/master/workflows/rrna-ref.md) page? There, a new FASTA file is created. Since it's a new FASTA file, it has its own coordinates that are not related to a particular human reference genome.
